# nixpacks.toml
[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install --only-binary=:all: -r requirements.txt"]

[start]
cmd = "python3 s9_scanner.py"   # <- B3 se S9 mein change
